[package]
name = "todo"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.37", features = ["derive"] }
dirs = "6.0.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
