[package]
name = "todo"
version = "0.5.0"
edition = "2024"
description = "A simple CLI to-do application"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.37", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
rusqlite = { version = "0.34.0", features = ["bundled", "chrono"] }
